# Generated by Django 3.2.7 on 2021-09-29 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210928_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orderclient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.paymentmethod'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.shipment'),
            preserve_default=False,
        ),
    ]
