from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='core-index'),
    path('employees/', views.employees, name='core-employees'),
    path('clients/', views.clients, name='core-clients'),
    path('clients/edit/<int:pk>/', views.client_edit, name='core-clients-edit'),
    path('clients/delete/<int:pk>/', views.client_delete, name='core-clients-delete'),
    path('categories/', views.categories, name='core-categories'),
    path('categories/edit/<int:pk>/', views.category_edit, name='core-categories-edit'),
    path('categoris/delete/<int:pk>/', views.category_delete, name='core-categories-delete'),
    path('contracts/', views.contracts, name='core-contracts'),
    path('contracts/edit/<int:pk>/', views.contract_edit, name='core-contracts-edit'),
    path('contracts/delete/<int:pk>/', views.contract_delete, name='core-contracts-delete'),
    path('shipments/', views.shipments, name='core-shipments'),
    path('shipments/edit/<int:pk>/', views.shipment_edit, name='core-shipments-edit'),
    path('shipments/delete/<int:pk>/', views.shipment_delete, name='core-shipments-delete'),
    path('payments/', views.payments, name='core-payments'),
    path('payments/edit/<int:pk>/', views.payment_edit, name='core-payments-edit'),
    path('payments/delete/<int:pk>/', views.payment_delete, name='core-payments-delete'),
    path('series/', views.series, name='core-series'),
    path('series/edit/<int:pk>/', views.series_edit, name='core-series-edit'),
    path('series/delete/<int:pk>/', views.series_delete, name='core-series-delete'),
    path('vendors/', views.vendors, name='core-vendors'),
    path('vendors/edit/<int:pk>/', views.vendor_edit, name='core-vendors-edit'),
    path('vendors/delete/<int:pk>/', views.vendor_delete, name='core-vendors-delete'),
    path('products/', views.products, name='core-products'),
    path('products/edit/<int:pk>/', views.product_edit, name='core-products-edit'),
    path('products/delete/<int:pk>/', views.product_delete, name='core-products-delete'),
    path('orders/', views.orders, name='core-orders'),
    path('orders/edit/<int:pk>/', views.order_edit, name='core-orders-edit'),
    path('orders/delete/<int:pk>/', views.order_delete, name='core-orders-delete'),
]